import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
from wordcloud import WordCloud, ImageColorGenerator


palavras= "Josué TE AMAMOS CARLA Atalanta Fernando Neto Porchat Sharon Pedro Castro Napoli Pará #EuropaLeagueNaESPN #AndJustLikeThat  Leicester jay park COBRA KAI NEVER DIES Machado #ocravoearosa robby #TheGameAwards #SUGAxJuiceWRLD olivia wilde Pirlo Interlagos Nova Zelândia Nubank Douglas Souza Stefania Motel Afrodite Glória Maria leighton CLIPE I&R MORAL DA HISTÓRIA Kami haak Villarreal Primavera Sound Engin Português Brasil 247 Samantha Paulinho BC Raff Raffa Márcia Pinheiro Tory Renata Lo Prete Petruchio Maldini Vendo 2 camila loures Touro de Ouro Kimberly Josué TE AMAMOS CARLA Fernando Neto Pedro Castro Napoli Atalanta Pará Sharon Porchat COBRA KAI NEVER DIES jay park robby Leicester Machado #OCravoEARosa #AndJustLikeThat #EuropaLeagueNaESPN #SUGAxJuiceWRLD #TheGameAwards olivia wilde Interlagos Pirlo Nova Zelândia Nubank Motel Afrodite Stefania Márcia Pinheiro Glória Maria Kami leighton haak CLIPE I&R MORAL DA HISTÓRIA Primavera Sound Douglas Souza Paulinho raffa BC Raff Tory Petruchio Renata Lo Prete Português Samantha Seedorf Romero camila loures Bolsa de Valores It Takes Two GOTY Brasil 247 Touro de Ouro Josué TE AMAMOS CARLA Fernando Neto Pedro Castro Pará Machado robby COBRA KAI NEVER DIES #OCravoEARosa Napoli #AndJustLikeThat jay park Leicester sharon #EuropaLeagueNaESPN Porchat #TheGameAwards #SUGAxJuiceWRLD Atalanta Interlagos Pirlo olivia wilde Nova Zelândia Motel Afrodite Márcia Pinheiro Nubank CLIPE I&R MORAL DA HISTÓRIA haak leighton Glória Maria Seedorf Primavera Sound Stefania Paulinho BC Raff Vaca Magra Kimmich Tory Bolsa de Valores Raffa Português petruchio Renata Lo Prete Kami Romero Touro de Ouro Giovanni Maldini Alfonso Douglas Souza Josué Fernando Neto TE AMAMOS CARLA Pedro Castro Pará COBRA KAI NEVER DIES #OCravoEARosa Machado robby Napoli #AndJustLikeThat jay park Leicester #EuropaLeagueNaESPN #TheGameAwards Interlagos #SUGAxJuiceWRLD olivia wilde Pirlo Porchat Motel Afrodite Márcia Pinheiro CLIPE I&R MORAL DA HISTÓRIA haak sharon Nubank Nova Zelândia Primavera Sound Paulinho Seedorf Jamie Jones BC Raff Vaca Magra Kimmich Giovanni Português Glória Maria Bolsa de Valores Kami Petruchio Romero raffa Stefania Renata Lo Prete Touro de Ouro Maldini leighton Alfonso Douglas Souza Tory Josué Fernando Neto Pedro Castro TE AMAMOS CARLA COBRA KAI NEVER DIES Pará Machado #OCravoEARosa robby jay park #AndJustLikeThat Interlagos olivia wilde #TheGameAwards #SUGAxJuiceWRLD Pirlo #SescRespeiteOsProfessores Márcia Pinheiro Motel Afrodite Porchat CLIPE I&R MORAL DA HISTÓRIA haak Primavera Sound Nubank bc raff Nova Zelândia Kimmich Glória Maria jamie jones jaehyun Samantha Vaca Magra Giovanni Alfonso Paulinho Bolsa de Valores Seedorf Petruchio Touro de Ouro Kami Raffa Leicester Português It Takes Two Romero Renata Lo Prete Stefania Tory Mattos Douglas Souza"
wordcloud = WordCloud(background_color="black", width=1600, height=800).generate(palavras)
plt.imshow(wordcloud)
wordcloud.to_file("nuvem.png")