import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
from wordcloud import WordCloud, ImageColorGenerator


palavras= "Barcelona Barça #ClipeTVZGirlFromRio #ClipeTVZMorena Benfica Chelsea #ClipeTVZModoTurbo Sané Europa League Stegen Cafu Pará #5SOS2011 Carvalhal #CasaDaChampions Xavi Muller Sevilla Dembele Werner Matic Alerj Coutinho GANHA O JOGO PRIOR UNIAO LOBINHOS 1FIGHT 4 BTS DAESANG Liga Europa Davies Dínamo QUACKITY Mingueza Manchester Jean Mota Florida Selic Juventus Lille PRIMEIRA VEZ NERRARE Piqué Dest Nenê Depay Claudinho yelena Atalanta Roubar Lenglet bruyne Villarreal Coman Barcelona Barça #ClipeTVZGirlFromRio #ClipeTVZMorena Benfica Chelsea #ClipeTVZModoTurbo Sané Europa League Stegen Cafu Pará #5SOS2011 Champions Xavi Carvalhal Muller #Walls Sevilla Dembele Werner Coutinho Alerj Davies Matic Liga Europa GANHA O JOGO PRIOR Mingueza 1FIGHT 4 BTS DAESANG Dínamo UNIAO LOBINHOS QUACKITY Manchester Claudinho Jean Mota Florida Lille Depay Juventus Piqué Dest Atalanta primeira vez nerrare yelena Selic Nenê Lenglet Roubar bruyne Coman Barcelona Barça #ClipeTVZGirlFromRio #ClipeTVZMorena Chelsea Benfica Sané #ClipeTVZModoTurbo Europa League Stegen Cafu Pará #CasaDaChampions Xavi Muller Carvalhal Dembele Sevilla #5SOS2011 Werner Coutinho Davies Alerj Dinamo GANHA O JOGO PRIOR Liga Europa Mingueza 1FIGHT 4 BTS DAESANG Manchester Claudinho QUACKITY Jean Mota Juventus Dest Piqué Depay Florida Lille Atalanta Lenglet yelena Selic Roubar PRIMEIRA VEZ NERRARE bruyne Coman Bartomeu Nenê Kiev Villarreal Barcelona Barça #ClipeTVZGirlFromRio #ClipeTVZMorena Chelsea Benfica Sané Europa League Stegen #ClipeTVZModoTurbo Cafu Pará #CasaDaChampions Xavi Muller Dembele Carvalhal Coutinho Sevilla Werner #Walls Davies Dínamo Alerj Mingueza GANHA O JOGO PRIOR Liga Europa Manchester Claudinho Piqué Depay 1FIGHT 4 BTS DAESANG Dest Juventus Jean Mota Lille Florida Lenglet Atalanta Yelena QUACKITY Bruyne Coman Roubar Bartomeu Neuer Kiev Nenê Villarreal Lukaku Barcelona Barça #ClipeTVZGirlFromRio Chelsea Benfica #ClipeTVZMorena Sané Stegen Europa League #ClipeTVZModoTurbo Cafu #CasaDaChampions Pará Xavi Dembele Muller Coutinho Werner Carvalhal Sevilla Davies Dínamo #Walls Mingueza GANHA O JOGO PRIOR Alerj Claudinho Liga Europa Manchester Piqué Dest 1FIGHT 4 BTS DAESANG Depay Juventus Jean Mota Lenglet Yelena bruyne Coman Kiev Bartomeu Roubar Lille Neuer Atalanta Lukaku Busquets Nenê Florida Talisca"
wordcloud = WordCloud(background_color="black", width=1600, height=800).generate(palavras)
plt.imshow(wordcloud)
wordcloud.to_file("nuvem.png")